on: push
name: deploy
jobs:
  deploy:
    name: deploy to cluster
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
        with:
          repository: 'ilanssari/odemo'
          ref: 'master'
    - name: deploy to cluster
      uses: steebchen/kubectl@v1.0.0
      env:
        KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
        KUBECTL_VERSION: "1.15"
      with:
        args: get namespaces